# Generated by Django 5.0.2 on 2025-05-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltip',
            name='last_served',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
